sudo: required

language: bash

dist: focal

- before_install:
  - apt-get install python3-pip==21.1.1
  - apt-get install libcairo2-dev
  - apt-get install libmysqlclient-dev

- install:
  - pip3 install -r requirements.txt

script: 
  - 
  - echo "Shell Script Execution Success!"
