# Language Interpreter to use while executing tests
language: bash

# Enable super user level permissions
sudo: required

# Command to use Ubuntu 20.04 LTS
dist: focal
  
# Command to install dependencies before install phase
before_install:
  - apt install python3-pip==21.1.1
  - apt-get install libcairo2-dev
  - apt-get update
  - apt-get upgrade -y

# Command to install dependencies
install:
  - pip3 install -r requirements.txt

# Test Scripts
script: 
  - python3 tester.py
  - echo "Travis Testing Success!"