language: bash

sudo: required

dist: focal

# Run series of commands that will run before test runs
- before_install:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install python3-pip==21.1.1

- install:
  - pip3 install -r requirements.txt

script: 
  - chmod +x tester.py
  - ./tester.py
  - echo "Shell Script Execution Success!"
