# Language Interpreter to use while executing tests
language: bash

# Enable super user level permissions
sudo: required

# Command to use Ubuntu 20.04 LTS
dist: focal
  
# Command to install dependencies before install phase
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt install python3-pip
  - sudo apt-get install libcairo2-dev
  - sudo apt-get install libmysqlclient-dev
  - sudo apt-get install -y language-selector-common
  - sudo apt-get update
  - sudo apt-get upgrade -y

# Command to install dependencies
install:
  - pip3 install -r requirements.txt

# Test Scripts
script: 
  - python3 dags/tester.py
  - echo "Travis Testing Success!"