# Language Interpreter to use while executing tests
language: bash

# Enable super user level permissions
sudo: required

# Command to use Ubuntu 20.04 LTS
dist: focal
  
# Command to install dependencies before install phase
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade -y
  - sudo apt install -qq python3-pip
  - sudo apt-get install -qq libcairo2-dev
  - sudo apt-get install -qq libmysqlclient-dev
  - sudo apt-get install -y language-selector-common
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade -y

# Command to install dependencies
install:
  - pip3 install -r requirements.txt -q

# Test Scripts
script: 
  - python3 dags/tester.py
  - echo "Travis Testing Success!"